/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WebPropertySummary } from './web-property-summary';


export interface AccountSummary { 
    id?: string | null;
    kind?: string | null;
    name?: string | null;
    starred?: boolean | null;
    webProperties?: Array<WebPropertySummary> | null;
    eTag?: string | null;
}

