/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountSummary } from './account-summary';


export interface AccountSummaries { 
    items?: Array<AccountSummary> | null;
    itemsPerPage?: number | null;
    kind?: string | null;
    nextLink?: string | null;
    previousLink?: string | null;
    startIndex?: number | null;
    totalResults?: number | null;
    username?: string | null;
    eTag?: string | null;
}

