/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAMetricHeader } from './ga-metric-header';


export interface GAColumnHeader { 
    dimensions?: Array<string> | null;
    metricHeader?: GAMetricHeader;
    eTag?: string | null;
}

