/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GADateRange } from './ga-date-range';


export interface GACohort { 
    dateRange?: GADateRange;
    name?: string | null;
    type?: string | null;
    eTag?: string | null;
}

