/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAMetadataDimensionDto } from './ga-metadata-dimension-dto';


export interface GADimensionGroupingDto { 
    uiName?: string | null;
    children?: Array<GAMetadataDimensionDto> | null;
}

