/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAPivotValueRegion } from './ga-pivot-value-region';


export interface GADateRangeValues { 
    pivotValueRegions?: Array<GAPivotValueRegion> | null;
    values?: Array<string> | null;
    eTag?: string | null;
}

