/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GADimensionFilter { 
    caseSensitive?: boolean | null;
    dimensionName?: string | null;
    expressions?: Array<string> | null;
    not?: boolean | null;
    operator__?: string | null;
    eTag?: string | null;
}

