/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GASegmentDefinition } from './ga-segment-definition';


export interface GADynamicSegment { 
    name?: string | null;
    sessionSegment?: GASegmentDefinition;
    userSegment?: GASegmentDefinition;
    eTag?: string | null;
}

