/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAMetadataMetricDto } from './ga-metadata-metric-dto';


export interface GAMetricGroupingDto { 
    uiName?: string | null;
    children?: Array<GAMetadataMetricDto> | null;
}

