/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GADimensionGroupingDto } from './ga-dimension-grouping-dto';
import { AccountSummaries } from './account-summaries';
import { GAMetricGroupingDto } from './ga-metric-grouping-dto';


export interface GAMetadataDto { 
    accountSummaries?: AccountSummaries;
    metricGroupings?: Array<GAMetricGroupingDto> | null;
    dimensionGroupings?: Array<GADimensionGroupingDto> | null;
}

