/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAMetricHeaderEntry } from './ga-metric-header-entry';
import { GAPivotHeader } from './ga-pivot-header';


export interface GAMetricHeader { 
    metricHeaderEntries?: Array<GAMetricHeaderEntry> | null;
    pivotHeaders?: Array<GAPivotHeader> | null;
    eTag?: string | null;
}

