/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAMetricFilter } from './ga-metric-filter';


export interface GAMetricFilterClause { 
    filters?: Array<GAMetricFilter> | null;
    operator__?: string | null;
    eTag?: string | null;
}

