/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GAMetadataMetricDto { 
    id?: string | null;
    kind?: string | null;
    description?: string | null;
    group?: string | null;
    uiName?: string | null;
}

