/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAPivotHeaderEntry } from './ga-pivot-header-entry';


export interface GAPivotHeader { 
    pivotHeaderEntries?: Array<GAPivotHeaderEntry> | null;
    totalPivotGroupsCount?: number | null;
    eTag?: string | null;
}

