/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAMetricHeaderEntry } from './ga-metric-header-entry';


export interface GAPivotHeaderEntry { 
    dimensionNames?: Array<string> | null;
    dimensionValues?: Array<string> | null;
    metric?: GAMetricHeaderEntry;
    eTag?: string | null;
}

