/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAColumnHeader } from './ga-column-header';
import { GAReportData } from './ga-report-data';


export interface GAReport { 
    columnHeader?: GAColumnHeader;
    data?: GAReportData;
    nextPageToken?: string | null;
    eTag?: string | null;
}

