/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GADateRangeValues } from './ga-date-range-values';
import { GAReportRow } from './ga-report-row';


export interface GAReportData { 
    isDataGolden?: boolean | null;
    maximums?: Array<GADateRangeValues> | null;
    minimums?: Array<GADateRangeValues> | null;
    rowCount?: number | null;
    rows?: Array<GAReportRow> | null;
    samplesReadCounts?: Array<number> | null;
    samplingSpaceSizes?: Array<number> | null;
    totals?: Array<GADateRangeValues> | null;
    eTag?: string | null;
}

