/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GADynamicSegment } from './ga-dynamic-segment';


export interface GASegment { 
    dynamicSegment?: GADynamicSegment;
    segmentId?: string | null;
    eTag?: string | null;
}

