/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GASimpleSegment } from './ga-simple-segment';
import { GASequenceSegment } from './ga-sequence-segment';


export interface GASegmentFilter { 
    not?: boolean | null;
    sequenceSegment?: GASequenceSegment;
    simpleSegment?: GASimpleSegment;
    eTag?: string | null;
}

