/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GASegmentMetricFilter { 
    comparisonValue?: string | null;
    maxComparisonValue?: string | null;
    metricName?: string | null;
    operator__?: string | null;
    scope?: string | null;
    eTag?: string | null;
}

