/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAOrFiltersForSegment } from './gaor-filters-for-segment';


export interface GASegmentSequenceStep { 
    matchType?: string | null;
    orFiltersForSegment?: Array<GAOrFiltersForSegment> | null;
    eTag?: string | null;
}

