/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GASegmentMetricFilter } from './ga-segment-metric-filter';
import { GASegmentDimensionFilter } from './ga-segment-dimension-filter';


export interface GASegmentFilterClause { 
    dimensionFilter?: GASegmentDimensionFilter;
    metricFilter?: GASegmentMetricFilter;
    not?: boolean | null;
    eTag?: string | null;
}

