/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GASegmentSequenceStep } from './ga-segment-sequence-step';


export interface GASequenceSegment { 
    firstStepShouldMatchFirstHit?: boolean | null;
    segmentSequenceSteps?: Array<GASegmentSequenceStep> | null;
    eTag?: string | null;
}

