/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GASegmentFilterClause } from './ga-segment-filter-clause';


export interface GAOrFiltersForSegment { 
    segmentFilterClauses?: Array<GASegmentFilterClause> | null;
    eTag?: string | null;
}

