/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileSummary { 
    id?: string | null;
    kind?: string | null;
    name?: string | null;
    starred?: boolean | null;
    type?: string | null;
    eTag?: string | null;
}

