/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Role = 'Undefined' | 'NotSet' | 'Administrator' | 'Marketer' | 'ClientRepresentative';

export const Role = {
    Undefined: 'Undefined' as Role,
    NotSet: 'NotSet' as Role,
    Administrator: 'Administrator' as Role,
    Marketer: 'Marketer' as Role,
    ClientRepresentative: 'ClientRepresentative' as Role
};

