/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SMReportType = 'Undefined' | 'NotSet' | 'GA' | 'YD';

export const SMReportType = {
    Undefined: 'Undefined' as SMReportType,
    NotSet: 'NotSet' as SMReportType,
    Ga: 'GA' as SMReportType,
    Yd: 'YD' as SMReportType
};

