/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SMReportType } from './sm-report-type';


export interface SMSourceCreateUpdateDto { 
    id?: number;
    clientId?: number;
    name?: string | null;
    type?: SMReportType;
    rawData?: string | null;
    rawMetadata?: string | null;
}

