/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GAReportRequest } from './ga-report-request';
import { GASourceMetadataDto } from './ga-source-metadata-dto';


export interface SMSourceUpdateGADataDto { 
    id?: number;
    reportRequests?: Array<GAReportRequest> | null;
    metadata?: GASourceMetadataDto;
}

