/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SMSourceFilterOperator = 'EQUALS' | 'NOT_EQUALS' | 'IN' | 'NOT_IN' | 'GREATER_THAN' | 'LESS_THAN' | 'CONTAINS';

export const SMSourceFilterOperator = {
    Equals: 'EQUALS' as SMSourceFilterOperator,
    NotEquals: 'NOT_EQUALS' as SMSourceFilterOperator,
    In: 'IN' as SMSourceFilterOperator,
    NotIn: 'NOT_IN' as SMSourceFilterOperator,
    GreaterThan: 'GREATER_THAN' as SMSourceFilterOperator,
    LessThan: 'LESS_THAN' as SMSourceFilterOperator,
    Contains: 'CONTAINS' as SMSourceFilterOperator
};

