/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Модель регистрации пользователя.
 */
export interface UserRegisterDto { 
    /**
     * Имя пользователя.
     */
    name?: string | null;
    /**
     * Адрес электронной почты.
     */
    email?: string | null;
    /**
     * Пароль.
     */
    password?: string | null;
}

