/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


/**
 * Модель ответа аутентификации пользователя.
 */
export interface UserAuthResponseDto { 
    /**
     * ID профиля пользователя (не самого пользователя).
     */
    id?: number;
    /**
     * JWT-токен доступа.
     */
    token?: string | null;
    /**
     * Имя пользователя.
     */
    name?: string | null;
    role?: Role;
}

