/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileSummary } from './profile-summary';


export interface WebPropertySummary { 
    id?: string | null;
    internalWebPropertyId?: string | null;
    kind?: string | null;
    level?: string | null;
    name?: string | null;
    profiles?: Array<ProfileSummary> | null;
    starred?: boolean | null;
    websiteUrl?: string | null;
    eTag?: string | null;
}

