/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type YDClientType = 'CLIENT' | 'SUBCLIENT' | 'AGENCY';

export const YDClientType = {
    Client: 'CLIENT' as YDClientType,
    Subclient: 'SUBCLIENT' as YDClientType,
    Agency: 'AGENCY' as YDClientType
};

