/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SMSourceFilter } from './sm-source-filter';


export interface YDStatisticsRequestDto { 
    filters?: Array<SMSourceFilter> | null;
    fieldNames?: Array<string> | null;
    startDate?: string | null;
    endDate?: string | null;
    token?: string | null;
}

