/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YDSourceMetadataMetric } from './yd-source-metadata-metric';
import { YDSourceMetadataFilter } from './yd-source-metadata-filter';
import { YDClient } from './yd-client';


export interface YDSourceMetadataDto { 
    clients?: Array<YDClient> | null;
    metrics?: Array<YDSourceMetadataMetric> | null;
    filters?: Array<YDSourceMetadataFilter> | null;
}

