/**
 * Shibametrics API
 * Shibametrics API Reference
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type YDYesNo = 'YES' | 'NO';

export const YDYesNo = {
    Yes: 'YES' as YDYesNo,
    No: 'NO' as YDYesNo
};

